In [1]:
marks=[90,80,75,60]

total=0
for mark in marks:
    total+=mark

average=total/len(marks)
print("Average mark:", average)

Average mark: 76.25


In [3]:
import numpy as np

marks=np.array([90,80,75,60])
average=np.mean(marks)
print("Average mark:", average)

sum=np.sum(marks)
min=np.min(marks)
max=np.max(marks)

std=np.std(marks)

print(f'Sum {sum}, Min {min}, Max {max}, Std {std}')


Average mark: 76.25
Sum 305, Min 60, Max 90, Std 10.825317547305483


In [4]:
prices=np.array([10,20,30,40])

print(prices[0])


10


In [5]:
students=[[90,80,70],[80,76,34],[45,56,65]]
students

[[90, 80, 70], [80, 76, 34], [45, 56, 65]]

In [6]:
np_students=np.array(students)
np_students

array([[90, 80, 70],
       [80, 76, 34],
       [45, 56, 65]])

In [ ]:
np_students.shape #rows and the columns

(3, 3)

In [20]:
#generate a zero array of size 4x2

x=np.full((4,2),2)
x

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2]])

In [21]:
y=np.ones((2,4)) # 2 x 4
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
z=x.dot(y)
z

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [11]:
zeros=np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
fives=ones*5
fives

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [14]:
sixs=fives+ones
sixs

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [15]:
tens=sixs+4
tens

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [26]:
result=tens*sixs
result

array([[60., 60., 60.],
       [60., 60., 60.],
       [60., 60., 60.]])

In [29]:
result2=result.flatten()
result2

array([60., 60., 60., 60., 60., 60., 60., 60., 60.])

In [30]:
x=np.array([[1,2],[3,4]])

x

array([[1, 2],
       [3, 4]])

In [31]:
y=x.transpose()
y

array([[1, 3],
       [2, 4]])